name:                readlinec
version:             0.1.0.0
github:              "Christophe1997/readlinec"
license:             BSD3
author:              "Christophe Shen"
maintainer:          "hey_christophe@outlook.com"
copyright:           "Christophe Shen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Christophe1997/readlinec#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

tests:
  readlinec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - readlinec
